### ISSUE TITLE
Moon-phases card not show

### ISSUE THREAD

**Issue by PrzemekSkw** [jeremyhamm/home-assistant-moon#2]
Hello, I have HA installed on Debian 11. I add:
```
sensor:
- platform: moon
```
to my `configuration.yaml` file and copy images and moon.js file to `/homeassistant/www/moon-phases/` folder.
I add to Configuration>Dashboards>Resources:
url: /local/moon-phases/moon.js
select type javascript module

I add homeassistant user/group and 777 permissions. 
but canot see any card or entity in HA. I reboot server and cleas browser cache.

![Zrzut ekranu z 2021-10-26 11-29-01](https://user-images.githubusercontent.com/25219988/138851094-87102fe9-6b1c-43b4-9ee3-f824280e8144.png)

Regards.

**Comment by jeremyhamm** [comment]
I have had this happen with other custom cards.  A few things that may help

- Try clearing your browser cache
- Restart home assistant
- Ensure you have the `moon` entity enabled

**Comment by PrzemekSkw** [comment]
Hi, @jeremyhamm I update to 2021.10.6 and moon sensor works now but card is still not visible. When I add card as You show everything disapeared from my Dashboard.
