### ISSUE TITLE
Moon image not displayed

### ISSUE THREAD

**Issue by gene2610** [jeremyhamm/home-assistant-moon#5]
I am on HA 2022.8.7 and trying to use the moon-phases card. I have installed per the instructions and the card displays the date and moon phase text but not the image. When I try to display the image in a new window it states not found. The moon-phases folder is in the www folder and the images folder in in the moon-phases folder. Any thoughts on the problem?

**Comment by gene2610** [comment]
SOLVED. I managed to solve this. I edited line 124 from this

`<img src="/hacsfiles/moon-phases/images/${phase.name}.png" class="img">`

to the following

`<img src="/local/moon-phases/images/${phase.name}.png" class="img">`

There is 1 change;  'hacsfiles' to 'local' since files are in www folder and not www/community. The image now appears as it should.

**Comment by gene2610** [comment]
Solved

**Comment by maijo366** [comment]
> SOLVED. I managed to solve this. I edited line 124 from this
> 
> `<img src="/hacsfiles/moon-phases/images/${phase.name}.png" class="img">`
> 
> to the following
> 
> `<img src="/local/moon-phases/images/${phase.name}.png" class="img">`
> 
> There is 1 change; 'hacsfiles' to 'local' since files are in www folder and not www/community. The image now appears as it should.

This do not help for me.

No Images displayed.
